title: Victor Polozov
description: Software Engineer and Technology Professional | Personal Portfolio & CV | Exploring ideas at the intersection of technology and innovation
baseurl: ""
url: "https://vpolozov.github.io" 

# Theme settings
remote_theme: piazzai/hacked-jekyll

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never

# **Forest Theme**
color_bg: gray-9
color_punct: green-4
color_key: green-8
color_value: teal-6
color_hover: green-3
